### ISSUE TITLE
感谢天苯菊苣

### ISSUE THREAD

**Issue by ImBearChild** [Universebenzene/wps-office-fonts#2]
我找这字体半天了，感谢天苯菊苣，做到了连 Internet Archive 都没有做到的事情。

**Comment by Universebenzene** [comment]
我不是菊苣😞

只是早年在gentoo-zh上装过，distfiles里deb包一直存着，发现wps-community没了之后就抢救回来了。都是gentoo-zh的菊苣们厉害
